spring.application.name=medicamentos
# Conexão com o Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tcc_medicamentos?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Configurações do Hibernate (Mágica do Spring)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true